//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TestVersioning.Models
{
    public partial class SimplifiedMessage
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime Created { get; set; }
        public byte[] Version { get; set; }
        public System.DateTime Modified { get; set; }
    }
    
}
