//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HmsModel", "FK_Hms_User_Default_message_type", "Message_Type", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFrameworkManyToMany.MessageType), "Hms_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Hms_User), true)]
[assembly: EdmRelationshipAttribute("HmsModel", "FK_Hms_User_Tab_Hms_user", "Hms_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFrameworkManyToMany.Hms_User), "Hms_User_Tab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Tab), true)]
[assembly: EdmRelationshipAttribute("HmsModel", "Hms_User_Tab_Message_Types", "Hms_User_Tab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Tab), "Message_Type", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.MessageType))]
[assembly: EdmRelationshipAttribute("HmsModel", "Hms_User_Tab_Pharmacy", "Hms_User_Tab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Tab), "Pharmacy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Pharmacy))]
[assembly: EdmRelationshipAttribute("HmsModel", "Hms_User_Tab_Priority", "Hms_User_Tab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Tab), "Priority", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkManyToMany.Priority))]

#endregion

namespace EntityFrameworkManyToMany
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HmsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HmsEntities object using the connection string found in the 'HmsEntities' section of the application configuration file.
        /// </summary>
        public HmsEntities() : base("name=HmsEntities", "HmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HmsEntities object.
        /// </summary>
        public HmsEntities(string connectionString) : base(connectionString, "HmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HmsEntities object.
        /// </summary>
        public HmsEntities(EntityConnection connection) : base(connection, "HmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hms_User> Hms_User
        {
            get
            {
                if ((_Hms_User == null))
                {
                    _Hms_User = base.CreateObjectSet<Hms_User>("Hms_User");
                }
                return _Hms_User;
            }
        }
        private ObjectSet<Hms_User> _Hms_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tab> Tabs
        {
            get
            {
                if ((_Tabs == null))
                {
                    _Tabs = base.CreateObjectSet<Tab>("Tabs");
                }
                return _Tabs;
            }
        }
        private ObjectSet<Tab> _Tabs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MessageType> MessageTypes
        {
            get
            {
                if ((_MessageTypes == null))
                {
                    _MessageTypes = base.CreateObjectSet<MessageType>("MessageTypes");
                }
                return _MessageTypes;
            }
        }
        private ObjectSet<MessageType> _MessageTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pharmacy> Pharmacies
        {
            get
            {
                if ((_Pharmacies == null))
                {
                    _Pharmacies = base.CreateObjectSet<Pharmacy>("Pharmacies");
                }
                return _Pharmacies;
            }
        }
        private ObjectSet<Pharmacy> _Pharmacies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Priority> Priorities
        {
            get
            {
                if ((_Priorities == null))
                {
                    _Priorities = base.CreateObjectSet<Priority>("Priorities");
                }
                return _Priorities;
            }
        }
        private ObjectSet<Priority> _Priorities;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hms_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHms_User(Hms_User hms_User)
        {
            base.AddObject("Hms_User", hms_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tabs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTabs(Tab tab)
        {
            base.AddObject("Tabs", tab);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessageTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessageTypes(MessageType messageType)
        {
            base.AddObject("MessageTypes", messageType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pharmacies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPharmacies(Pharmacy pharmacy)
        {
            base.AddObject("Pharmacies", pharmacy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Priorities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPriorities(Priority priority)
        {
            base.AddObject("Priorities", priority);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HmsModel", Name="Hms_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hms_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hms_User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user_name">Initial value of the User_name property.</param>
        /// <param name="default_message_type">Initial value of the Default_message_type property.</param>
        /// <param name="locked">Initial value of the Locked property.</param>
        /// <param name="new_message_preference">Initial value of the New_message_preference property.</param>
        /// <param name="security_authorization">Initial value of the Security_authorization property.</param>
        public static Hms_User CreateHms_User(global::System.Int32 id, global::System.String user_name, global::System.Byte default_message_type, global::System.Boolean locked, global::System.Boolean new_message_preference, global::System.Int32 security_authorization)
        {
            Hms_User hms_User = new Hms_User();
            hms_User.Id = id;
            hms_User.User_name = user_name;
            hms_User.Default_message_type = default_message_type;
            hms_User.Locked = locked;
            hms_User.New_message_preference = new_message_preference;
            hms_User.Security_authorization = security_authorization;
            return hms_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_name
        {
            get
            {
                return _First_name;
            }
            set
            {
                OnFirst_nameChanging(value);
                ReportPropertyChanging("First_name");
                _First_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_name");
                OnFirst_nameChanged();
            }
        }
        private global::System.String _First_name;
        partial void OnFirst_nameChanging(global::System.String value);
        partial void OnFirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_name
        {
            get
            {
                return _Last_name;
            }
            set
            {
                OnLast_nameChanging(value);
                ReportPropertyChanging("Last_name");
                _Last_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_name");
                OnLast_nameChanged();
            }
        }
        private global::System.String _Last_name;
        partial void OnLast_nameChanging(global::System.String value);
        partial void OnLast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Initials
        {
            get
            {
                return _Initials;
            }
            set
            {
                OnInitialsChanging(value);
                ReportPropertyChanging("Initials");
                _Initials = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Initials");
                OnInitialsChanged();
            }
        }
        private global::System.String _Initials;
        partial void OnInitialsChanging(global::System.String value);
        partial void OnInitialsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_name
        {
            get
            {
                return _User_name;
            }
            set
            {
                OnUser_nameChanging(value);
                ReportPropertyChanging("User_name");
                _User_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_name");
                OnUser_nameChanged();
            }
        }
        private global::System.String _User_name;
        partial void OnUser_nameChanging(global::System.String value);
        partial void OnUser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Host_operator_id
        {
            get
            {
                return _Host_operator_id;
            }
            set
            {
                OnHost_operator_idChanging(value);
                ReportPropertyChanging("Host_operator_id");
                _Host_operator_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Host_operator_id");
                OnHost_operator_idChanged();
            }
        }
        private global::System.String _Host_operator_id;
        partial void OnHost_operator_idChanging(global::System.String value);
        partial void OnHost_operator_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Default_message_type
        {
            get
            {
                return _Default_message_type;
            }
            set
            {
                OnDefault_message_typeChanging(value);
                ReportPropertyChanging("Default_message_type");
                _Default_message_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Default_message_type");
                OnDefault_message_typeChanged();
            }
        }
        private global::System.Byte _Default_message_type;
        partial void OnDefault_message_typeChanging(global::System.Byte value);
        partial void OnDefault_message_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Locked
        {
            get
            {
                return _Locked;
            }
            set
            {
                OnLockedChanging(value);
                ReportPropertyChanging("Locked");
                _Locked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Locked");
                OnLockedChanged();
            }
        }
        private global::System.Boolean _Locked;
        partial void OnLockedChanging(global::System.Boolean value);
        partial void OnLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Invalid_time
        {
            get
            {
                return _Invalid_time;
            }
            set
            {
                OnInvalid_timeChanging(value);
                ReportPropertyChanging("Invalid_time");
                _Invalid_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Invalid_time");
                OnInvalid_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Invalid_time;
        partial void OnInvalid_timeChanging(Nullable<global::System.DateTime> value);
        partial void OnInvalid_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean New_message_preference
        {
            get
            {
                return _New_message_preference;
            }
            set
            {
                OnNew_message_preferenceChanging(value);
                ReportPropertyChanging("New_message_preference");
                _New_message_preference = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("New_message_preference");
                OnNew_message_preferenceChanged();
            }
        }
        private global::System.Boolean _New_message_preference;
        partial void OnNew_message_preferenceChanging(global::System.Boolean value);
        partial void OnNew_message_preferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Version
        {
            get
            {
                return StructuralObject.GetValidValue(_Version);
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Byte[] _Version;
        partial void OnVersionChanging(global::System.Byte[] value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Security_authorization
        {
            get
            {
                return _Security_authorization;
            }
            set
            {
                OnSecurity_authorizationChanging(value);
                ReportPropertyChanging("Security_authorization");
                _Security_authorization = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Security_authorization");
                OnSecurity_authorizationChanged();
            }
        }
        private global::System.Int32 _Security_authorization;
        partial void OnSecurity_authorizationChanging(global::System.Int32 value);
        partial void OnSecurity_authorizationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "FK_Hms_User_Default_message_type", "Message_Type")]
        public MessageType Message_Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessageType>("HmsModel.FK_Hms_User_Default_message_type", "Message_Type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessageType>("HmsModel.FK_Hms_User_Default_message_type", "Message_Type").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MessageType> Message_TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MessageType>("HmsModel.FK_Hms_User_Default_message_type", "Message_Type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MessageType>("HmsModel.FK_Hms_User_Default_message_type", "Message_Type", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "FK_Hms_User_Tab_Hms_user", "Hms_User_Tab")]
        public EntityCollection<Tab> Hms_User_Tab
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tab>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User_Tab");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tab>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User_Tab", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HmsModel", Name="MessageType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MessageType object.
        /// </summary>
        /// <param name="ordinal">Initial value of the Ordinal property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static MessageType CreateMessageType(global::System.Byte ordinal, global::System.String name)
        {
            MessageType messageType = new MessageType();
            messageType.Ordinal = ordinal;
            messageType.Name = name;
            return messageType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Ordinal
        {
            get
            {
                return _Ordinal;
            }
            set
            {
                if (_Ordinal != value)
                {
                    OnOrdinalChanging(value);
                    ReportPropertyChanging("Ordinal");
                    _Ordinal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ordinal");
                    OnOrdinalChanged();
                }
            }
        }
        private global::System.Byte _Ordinal;
        partial void OnOrdinalChanging(global::System.Byte value);
        partial void OnOrdinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HmsModel", Name="Pharmacy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pharmacy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pharmacy object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        public static Pharmacy CreatePharmacy(global::System.Int32 id, global::System.String name, global::System.String code)
        {
            Pharmacy pharmacy = new Pharmacy();
            pharmacy.Id = id;
            pharmacy.Name = name;
            pharmacy.Code = code;
            return pharmacy;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street1
        {
            get
            {
                return _Street1;
            }
            set
            {
                OnStreet1Changing(value);
                ReportPropertyChanging("Street1");
                _Street1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street1");
                OnStreet1Changed();
            }
        }
        private global::System.String _Street1;
        partial void OnStreet1Changing(global::System.String value);
        partial void OnStreet1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street2
        {
            get
            {
                return _Street2;
            }
            set
            {
                OnStreet2Changing(value);
                ReportPropertyChanging("Street2");
                _Street2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street2");
                OnStreet2Changed();
            }
        }
        private global::System.String _Street2;
        partial void OnStreet2Changing(global::System.String value);
        partial void OnStreet2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Timezone
        {
            get
            {
                return _Timezone;
            }
            set
            {
                OnTimezoneChanging(value);
                ReportPropertyChanging("Timezone");
                _Timezone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timezone");
                OnTimezoneChanged();
            }
        }
        private global::System.String _Timezone;
        partial void OnTimezoneChanging(global::System.String value);
        partial void OnTimezoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Last_polled
        {
            get
            {
                return _Last_polled;
            }
            set
            {
                OnLast_polledChanging(value);
                ReportPropertyChanging("Last_polled");
                _Last_polled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Last_polled");
                OnLast_polledChanged();
            }
        }
        private Nullable<global::System.DateTime> _Last_polled;
        partial void OnLast_polledChanging(Nullable<global::System.DateTime> value);
        partial void OnLast_polledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Configuration
        {
            get
            {
                return _Configuration;
            }
            set
            {
                OnConfigurationChanging(value);
                ReportPropertyChanging("Configuration");
                _Configuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Configuration");
                OnConfigurationChanged();
            }
        }
        private global::System.String _Configuration;
        partial void OnConfigurationChanging(global::System.String value);
        partial void OnConfigurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Version
        {
            get
            {
                return StructuralObject.GetValidValue(_Version);
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Byte[] _Version;
        partial void OnVersionChanging(global::System.Byte[] value);
        partial void OnVersionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HmsModel", Name="Priority")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Priority : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Priority object.
        /// </summary>
        /// <param name="ordinal">Initial value of the Ordinal property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="is_Default">Initial value of the Is_Default property.</param>
        /// <param name="due">Initial value of the Due property.</param>
        /// <param name="due_within">Initial value of the Due_within property.</param>
        /// <param name="due_within_time_period">Initial value of the Due_within_time_period property.</param>
        /// <param name="alert_within">Initial value of the Alert_within property.</param>
        /// <param name="alert_within_time_period">Initial value of the Alert_within_time_period property.</param>
        public static Priority CreatePriority(global::System.Byte ordinal, global::System.String name, global::System.Boolean is_Default, global::System.Byte due, global::System.Int16 due_within, global::System.Byte due_within_time_period, global::System.Int16 alert_within, global::System.Byte alert_within_time_period)
        {
            Priority priority = new Priority();
            priority.Ordinal = ordinal;
            priority.Name = name;
            priority.Is_Default = is_Default;
            priority.Due = due;
            priority.Due_within = due_within;
            priority.Due_within_time_period = due_within_time_period;
            priority.Alert_within = alert_within;
            priority.Alert_within_time_period = alert_within_time_period;
            return priority;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Ordinal
        {
            get
            {
                return _Ordinal;
            }
            set
            {
                if (_Ordinal != value)
                {
                    OnOrdinalChanging(value);
                    ReportPropertyChanging("Ordinal");
                    _Ordinal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ordinal");
                    OnOrdinalChanged();
                }
            }
        }
        private global::System.Byte _Ordinal;
        partial void OnOrdinalChanging(global::System.Byte value);
        partial void OnOrdinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Is_Default
        {
            get
            {
                return _Is_Default;
            }
            set
            {
                OnIs_DefaultChanging(value);
                ReportPropertyChanging("Is_Default");
                _Is_Default = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Is_Default");
                OnIs_DefaultChanged();
            }
        }
        private global::System.Boolean _Is_Default;
        partial void OnIs_DefaultChanging(global::System.Boolean value);
        partial void OnIs_DefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Due
        {
            get
            {
                return _Due;
            }
            set
            {
                OnDueChanging(value);
                ReportPropertyChanging("Due");
                _Due = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Due");
                OnDueChanged();
            }
        }
        private global::System.Byte _Due;
        partial void OnDueChanging(global::System.Byte value);
        partial void OnDueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Due_within
        {
            get
            {
                return _Due_within;
            }
            set
            {
                OnDue_withinChanging(value);
                ReportPropertyChanging("Due_within");
                _Due_within = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Due_within");
                OnDue_withinChanged();
            }
        }
        private global::System.Int16 _Due_within;
        partial void OnDue_withinChanging(global::System.Int16 value);
        partial void OnDue_withinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Due_within_time_period
        {
            get
            {
                return _Due_within_time_period;
            }
            set
            {
                OnDue_within_time_periodChanging(value);
                ReportPropertyChanging("Due_within_time_period");
                _Due_within_time_period = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Due_within_time_period");
                OnDue_within_time_periodChanged();
            }
        }
        private global::System.Byte _Due_within_time_period;
        partial void OnDue_within_time_periodChanging(global::System.Byte value);
        partial void OnDue_within_time_periodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Due_text_color
        {
            get
            {
                return _Due_text_color;
            }
            set
            {
                OnDue_text_colorChanging(value);
                ReportPropertyChanging("Due_text_color");
                _Due_text_color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Due_text_color");
                OnDue_text_colorChanged();
            }
        }
        private global::System.String _Due_text_color;
        partial void OnDue_text_colorChanging(global::System.String value);
        partial void OnDue_text_colorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Alert_within
        {
            get
            {
                return _Alert_within;
            }
            set
            {
                OnAlert_withinChanging(value);
                ReportPropertyChanging("Alert_within");
                _Alert_within = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Alert_within");
                OnAlert_withinChanged();
            }
        }
        private global::System.Int16 _Alert_within;
        partial void OnAlert_withinChanging(global::System.Int16 value);
        partial void OnAlert_withinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Alert_within_time_period
        {
            get
            {
                return _Alert_within_time_period;
            }
            set
            {
                OnAlert_within_time_periodChanging(value);
                ReportPropertyChanging("Alert_within_time_period");
                _Alert_within_time_period = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Alert_within_time_period");
                OnAlert_within_time_periodChanged();
            }
        }
        private global::System.Byte _Alert_within_time_period;
        partial void OnAlert_within_time_periodChanging(global::System.Byte value);
        partial void OnAlert_within_time_periodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alert_text_color
        {
            get
            {
                return _Alert_text_color;
            }
            set
            {
                OnAlert_text_colorChanging(value);
                ReportPropertyChanging("Alert_text_color");
                _Alert_text_color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alert_text_color");
                OnAlert_text_colorChanged();
            }
        }
        private global::System.String _Alert_text_color;
        partial void OnAlert_text_colorChanging(global::System.String value);
        partial void OnAlert_text_colorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Version
        {
            get
            {
                return StructuralObject.GetValidValue(_Version);
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Byte[] _Version;
        partial void OnVersionChanging(global::System.Byte[] value);
        partial void OnVersionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HmsModel", Name="Tab")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tab : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tab object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="ordinal">Initial value of the Ordinal property.</param>
        public static Tab CreateTab(global::System.Int32 id, global::System.Int32 userId, global::System.Byte ordinal)
        {
            Tab tab = new Tab();
            tab.Id = id;
            tab.UserId = userId;
            tab.Ordinal = ordinal;
            return tab;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Ordinal
        {
            get
            {
                return _Ordinal;
            }
            set
            {
                OnOrdinalChanging(value);
                ReportPropertyChanging("Ordinal");
                _Ordinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ordinal");
                OnOrdinalChanged();
            }
        }
        private global::System.Byte _Ordinal;
        partial void OnOrdinalChanging(global::System.Byte value);
        partial void OnOrdinalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "FK_Hms_User_Tab_Hms_user", "Hms_User")]
        public Hms_User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hms_User>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hms_User>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hms_User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hms_User>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hms_User>("HmsModel.FK_Hms_User_Tab_Hms_user", "Hms_User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "Hms_User_Tab_Message_Types", "Message_Type")]
        public EntityCollection<MessageType> MessageTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MessageType>("HmsModel.Hms_User_Tab_Message_Types", "Message_Type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MessageType>("HmsModel.Hms_User_Tab_Message_Types", "Message_Type", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "Hms_User_Tab_Pharmacy", "Pharmacy")]
        public EntityCollection<Pharmacy> Pharmacies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pharmacy>("HmsModel.Hms_User_Tab_Pharmacy", "Pharmacy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pharmacy>("HmsModel.Hms_User_Tab_Pharmacy", "Pharmacy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HmsModel", "Hms_User_Tab_Priority", "Priority")]
        public EntityCollection<Priority> Priorities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Priority>("HmsModel.Hms_User_Tab_Priority", "Priority");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Priority>("HmsModel.Hms_User_Tab_Priority", "Priority", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
